const GET_REPORT_FOR_PERIOD_REQUEST = "GET_REPORT_FOR_PERIOD_REQUEST";
const GET_REPORT_FOR_PERIOD_SUCCESS = "GET_REPORT_FOR_PERIOD_SUCCESS";
const GET_REPORT_FOR_PERIOD_FAIL = "GET_REPORT_FOR_PERIOD_FAIL";

export {
  GET_REPORT_FOR_PERIOD_FAIL,
  GET_REPORT_FOR_PERIOD_REQUEST,
  GET_REPORT_FOR_PERIOD_SUCCESS,
};
